<a href="https://colab.research.google.com/github/azzou02/EUblog/blob/main/Assignment_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this assignment we are going to work with data that was downloaded using using the [yfinance](https://pypi.org/project/yfinance/) library. It containst daily closing prices of all symbols.

In [1]:
from multiprocessing   import Pool
from tqdm import *
import pandas as pd

In [2]:
#Question 1: Explain what the code below is trying to do. Describe each step.
data = pd.read_csv("http://www.nasdaqtrader.com/dynamic/SymDir/nasdaqtraded.txt", sep='|')
data_clean = data[data['Test Issue'] == 'N']
symbols = set(data_clean['NASDAQ Symbol'].tolist())
data = pd.read_csv("http://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt", sep='|')
data_clean = data[data['Test Issue'] == 'N']
symbols = set(data_clean['NASDAQ Symbol'].tolist())

In [3]:
#Describe your answer below.
#Answer 1:
'''
the first line reads the data from the csv into a DataFrame using a built in function from the pandas library
the second line cleans the data so the DataFrame only includes rows where the 'Test Issue' column has the value 'N'
the third line converts the DataFrame's 'NASDAQ Symbol' column into a list then de-duplicates it by turning it to a set, which doesn't have an order
the fourth line reads the data from a different csv into a DataFrame, overwriting the data from the first line
the fifth line cleans the new data so the data frame only includes rows where the 'Test Issue' column has the value 'N', overwriting the previous cleaned data
the sixth line converts the DataFrame's 'NASDAQ Symbol' column into a set, overwriting the first set of symbols created in line 3
'''

"\nthe first line reads the data from the csv into a DataFrame using a built in function from the pandas library\nthe second line cleans the data so the DataFrame only includes rows where the 'Test Issue' column has the value 'N'\nthe third line converts the DataFrame's 'NASDAQ Symbol' column into a list then de-duplicates it by turning it to a set, which doesn't have an order\nthe fourth line reads the data from a different csv into a DataFrame, overwriting the data from the first line\nthe fifth line cleans the new data so the data frame only includes rows where the 'Test Issue' column has the value 'N', overwriting the previous cleaned data\nthe sixth line converts the DataFrame's 'NASDAQ Symbol' column into a set, overwriting the first set of symbols created in line 3\n"

In [4]:
!wget  -O stocks.parquet https://www.dropbox.com/s/gzpi950gfdz9dsk/stocks.parquet?dl=1 # lets download the data

--2026-01-09 04:05:54--  https://www.dropbox.com/s/gzpi950gfdz9dsk/stocks.parquet?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.81.18, 2620:100:6031:18::a27d:5112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.81.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/scl/fi/pm4vi37h059bx0du3ecj8/stocks.parquet?rlkey=8k31klc1tlf8bk4ocxpzbgm9c&dl=1 [following]
--2026-01-09 04:05:54--  https://www.dropbox.com/scl/fi/pm4vi37h059bx0du3ecj8/stocks.parquet?rlkey=8k31klc1tlf8bk4ocxpzbgm9c&dl=1
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uce903c6add827121c8de57f86c0.dl.dropboxusercontent.com/cd/0/inline/C4ldtnjE2WIpya2ROZjptGsUvkGwHjm-Ky1lxUHnMG4IteSAfQGqjkqMC7TayKxLhnPTpP-Q4d8j2xOcdNDgXVgSCJ5h53NTvGQ8ynzeTqMvDAZXXQVyUQa0qeDg8Dkkz5JBvqBqpjLFqglfAjsHYbR3/file?dl=1# [following]
--2026-01-09 04:05:55--  https://uce903c6add827121c8de57f86c0.dl.dropboxusercontent.com/cd/0/inline/C4ldtnjE2WIpya2ROZjptGsUvkGwHjm-Ky1lxUHnMG4IteSAfQGqjkqMC7TayKxLhnPTpP-Q4d8j2xOcdNDgXVgSCJ5h53NTvGQ8ynzeTqMvDAZXXQVyUQa0qeDg8Dkkz5JBvqBqpjLFqglfAjsHYbR3/file?dl=1
Resolving uce903c6add827121c8de57f86c0.dl.dropboxusercontent.com (uce903c6add827121c8de57f86c0.dl.dropboxusercontent.com)... 162.125.81.15, 2620:100:601c:15::a27d:60f
Connecting to uce903c6add827121c8de57f86c0.dl.dropboxusercontent.com (uce903c6add827121c8de57f86c0.dl.dropboxusercontent.com)|162.125.81.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/C4n8ZTUPQ0POms0ogoQfB8T_PBcP9sRybr7lf9ouN-Dl7CBYaBiz_kIdjr8Uvdg6wS8ef9GkkQXILhWI8Jw-_VxgAJQ3-Q0olfEJBBN87g1PMwrOaNL5ScspD2mXBjaejXkdnEXwf_N7pIqwlSB4in6rEfJ8oaTjtufX3K5-KZuPxDrp1X7S7uWCZWtf_zg1YtYjn6yq9EpbQf1GfzgiZPDHbxNU42F6uykzCgSprDEUXH-L_UZZ3A1F_U7GyQFWKjU-9aTFdL2kBfX6cNYT6Nx3Be_2AtIhSLK89WuRj73Dd6cqzY6UlR3Fuvy--3zEH8e9qg2YPcs4Z4LxaJQRtE3V5z7dXoIR5udp7oUhVe8STLFnNHgUH-sSU1rwKfPZ8Go/file?dl=1 [following]
--2026-01-09 04:05:55--  https://uce903c6add827121c8de57f86c0.dl.dropboxusercontent.com/cd/0/inline2/C4n8ZTUPQ0POms0ogoQfB8T_PBcP9sRybr7lf9ouN-Dl7CBYaBiz_kIdjr8Uvdg6wS8ef9GkkQXILhWI8Jw-_VxgAJQ3-Q0olfEJBBN87g1PMwrOaNL5ScspD2mXBjaejXkdnEXwf_N7pIqwlSB4in6rEfJ8oaTjtufX3K5-KZuPxDrp1X7S7uWCZWtf_zg1YtYjn6yq9EpbQf1GfzgiZPDHbxNU42F6uykzCgSprDEUXH-L_UZZ3A1F_U7GyQFWKjU-9aTFdL2kBfX6cNYT6Nx3Be_2AtIhSLK89WuRj73Dd6cqzY6UlR3Fuvy--3zEH8e9qg2YPcs4Z4LxaJQRtE3V5z7dXoIR5udp7oUhVe8STLFnNHgUH-sSU1rwKfPZ8Go/file?dl=1
Reusing existing connection to uce903c6add827121c8de57f86c0.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 678640589 (647M) [application/binary]
Saving to: ‘stocks.parquet’

stocks.parquet      100%[===================>] 647.20M  20.1MB/s    in 33s

2026-01-09 04:06:28 (19.6 MB/s) - ‘stocks.parquet’ saved [678640589/678640589]

In [5]:
!ls stocks.parquet -l #downloaded file

-rw-r--r-- 1 root root 678640589 Jan  9 04:06 stocks.parquet

In [ ]:
#Bonus question 1 - find on internet and write the command that will download the all data from the symbols list.

In [6]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.1)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [9]:
import yfinance as yf

small_list = list(symbols)[50:100]
symbols_data = yf.download(list(small_list), period="1wk", interval="1d")

/tmp/ipython-input-1721733567.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  symbols_data = yf.download(list(small_list), period="1wk", interval="1d")
[*********************100%***********************]  50 of 50 completed
ERROR:yfinance:
3 Failed downloads:
ERROR:yfinance:['EPR-C', 'PSA-N', 'LZM+']: YFPricesMissingError('possibly delisted; no price data found  (period=1wk) (Yahoo error = "No data found, symbol may be delisted")')

In [10]:
symbols_data.head(5)

Price      Adj Close                  Close                                   \
Ticker         EPR-C LZM+ PSA-N        ALSN       ASIX       AXTA       CARU
Date
2026-01-02       NaN  NaN   NaN   98.940002  17.219999  33.000000  30.540001
2026-01-05       NaN  NaN   NaN   97.970001  16.660000  33.070000  32.428001
2026-01-06       NaN  NaN   NaN  101.580002  17.820000  32.950001  32.626999
2026-01-07       NaN  NaN   NaN   99.459999  17.760000  32.439999  32.948002
2026-01-08       NaN  NaN   NaN  102.180000  18.180000  32.430000  34.376999

Price                                         ...  Volume                 \
Ticker            CBRE       CDRE       CGMM  ...    RAMP    RBLU   SLDR
Date                                          ...
2026-01-02  160.190002  41.119999  29.219999  ...  568800   49100    400
2026-01-05  164.399994  41.980000  29.750000  ...  492200   44600  19800
2026-01-06  166.919998  42.790001  30.240000  ...  352800  153400   1000
2026-01-07  166.330002  43.400002  29.950001  ...  679900   94500   1100
2026-01-08  165.960007  42.410000  30.230000  ...  598100  150500   3700

Price
Ticker        SNTH      SQM      SR        U     UMH      WPC    XEMD
Date
2026-01-02   29800   746300  323200  5135400  478500   831600  106300
2026-01-05   10000   824800  402300  5892700  602400  1656000  101400
2026-01-06   55000  1959300  348400  6924300  551100  1271400   45900
2026-01-07   40100  2318600  362900  4533500  711000  1679100   51200
2026-01-08  232900  1344700  268300  6730100  571400  1373500   55400

[5 rows x 253 columns]

In [ ]:
data=pd.read_parquet('stocks.parquet')

In [ ]:
data.head(1) # Below shows a sample of the data.
#date - describes the day of the price
#open - the price at which stock opened
#high - what was the intraday high
#low - what is the intraday low
#close - what was the closing price
#adj_close - the price calculated after adjusting for all future stock splits
#dividends - what are the dividends that were paid on the day.
#stock_splits - if the stock was split
#symbol the symbol of the stock

         date      open      high       low  ...  day  year  month  dayofweek
0  1962-01-02  0.131273  0.131273  0.124177  ...    2  1962      1    Tuesday

[1 rows x 14 columns]

In [ ]:
# Question 2 find top 20 best performer stocks - i.e. the stocks that provided the best return.
# if the stocks adj_close on the earliest date was X and the adj_close on the 2021-01-01 is y and the number of days elapsed between these dates is Z.
# Then return = Y/X/Z
# Sort the stocks by this return and find the top 20

In [ ]:
#Question 3: Create a copy of this notebook called assignment-aws and follow the instructions in readme to run the notebook on AWS compute instance.
# Compare performance of running natively on colab and colab+AWS