<a href="https://colab.research.google.com/github/azzou02/EUblog/blob/main/Assignment_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this assignment we are going to work with data that was downloaded using using the [yfinance](https://pypi.org/project/yfinance/) library. It containst daily closing prices of all symbols.

In [2]:
from multiprocessing   import Pool
from tqdm import *
import pandas as pd

In [7]:
#Question 1: Explain what the code below is trying to do. Describe each step.
data = pd.read_csv("http://www.nasdaqtrader.com/dynamic/SymDir/nasdaqtraded.txt", sep='|')
data_clean = data[data['Test Issue'] == 'N']
symbols = set(data_clean['NASDAQ Symbol'].tolist())
data = pd.read_csv("http://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt", sep='|')
data_clean = data[data['Test Issue'] == 'N']
symbols = set(data_clean['NASDAQ Symbol'].tolist())

In [ ]:
#Describe your answer below.
'''
Answer 1: the first line reads the data from the csv into a DataFrame using a built in function from the pandas library
          the second line cleans the data so the DataFrame only includes rows where the 'Test Issue' column has the value 'N'
          the third line converts the DataFrame's 'NASDAQ Symbol' column into a list then de-duplicates it by turning it to a set, which doesn't have an order
          the fourth line reads the data from a different csv into a DataFrame, overwriting the data from the first line
          the fifth line cleans the new data so the data frame only includes rows where the 'Test Issue' column has the value 'N', overwriting the previous cleaned data
          the sixth line converts the DataFrame's 'NASDAQ Symbol' column into a set, overwriting the first set of symbols created in line 3.
'''

In [3]:
!wget  -O stocks.parquet https://www.dropbox.com/s/gzpi950gfdz9dsk/stocks.parquet?dl=1 # lets download the data

--2026-01-09 02:34:24--  https://www.dropbox.com/s/gzpi950gfdz9dsk/stocks.parquet?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/scl/fi/pm4vi37h059bx0du3ecj8/stocks.parquet?rlkey=8k31klc1tlf8bk4ocxpzbgm9c&dl=1 [following]
--2026-01-09 02:34:24--  https://www.dropbox.com/scl/fi/pm4vi37h059bx0du3ecj8/stocks.parquet?rlkey=8k31klc1tlf8bk4ocxpzbgm9c&dl=1
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc152a49a47dcfa5d06a5c3c8cb7.dl.dropboxusercontent.com/cd/0/inline/C4ktsSkq5bDLOFz98t5SHKHeOQeuxL6BaL9mz9AlhBnCNfiO4dSexvDPqEtnvbkFHFBpT4ofKsPxlkDBp-WHboepQnkxzq0LzvGSkqsZZ1QGl_X437bnUqnqKQ6wavkUSL29L7MFDrSun8LX0Zo8oSqz/file?dl=1# [following]
--2026-01-09 02:34:25--  https://uc152a49a47dcfa5d06a5c3c8cb7.dl.dropboxusercontent.com/cd/0/inline/C4ktsSkq5bDLOFz98t5SHKHeOQeuxL6BaL9mz9AlhBnCNfiO4dSexvDPqEtnvbkFHFBpT4ofKsPxlkDBp-WHboepQnkxzq0LzvGSkqsZZ1QGl_X437bnUqnqKQ6wavkUSL29L7MFDrSun8LX0Zo8oSqz/file?dl=1
Resolving uc152a49a47dcfa5d06a5c3c8cb7.dl.dropboxusercontent.com (uc152a49a47dcfa5d06a5c3c8cb7.dl.dropboxusercontent.com)... 162.125.5.15, 2620:100:601d:15::a27d:50f
Connecting to uc152a49a47dcfa5d06a5c3c8cb7.dl.dropboxusercontent.com (uc152a49a47dcfa5d06a5c3c8cb7.dl.dropboxusercontent.com)|162.125.5.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/C4lvZ3e0ScBQXQiBDfjI_6QT8_p3C0ARqMCpHiCRjjKY7SGuh47FR5ob0FqBKBMxkgSlT0DHn0-ZziH-VuQ2R9IDYyTQAQVzUinneBCSSo6Hbxqva8zMwK8UCBSO14jqammiqMeSNkqSY13AGU4php9xn0guZUWCR6w93wxkOxMyWt2qlbPficXVX12PLwj1TTXix4REbcIhP-dt3Srsqa8MkR-yhdfmgEGJyJnY6-9RTE_wMweUJO3OY6hpC4ziOnvF5tirVKFgPSZA5CfTN-f3ZIc_4LsvjxlG66TvUeJdzeiZfUvEkOKhhaMkNjo0iPoMUkHzuorz6cthWwW6vzDCPyljjZNLPp3LIOJY3Pgv5ma3XjC3tsNVJXUe4FjG_I0/file?dl=1 [following]
--2026-01-09 02:34:25--  https://uc152a49a47dcfa5d06a5c3c8cb7.dl.dropboxusercontent.com/cd/0/inline2/C4lvZ3e0ScBQXQiBDfjI_6QT8_p3C0ARqMCpHiCRjjKY7SGuh47FR5ob0FqBKBMxkgSlT0DHn0-ZziH-VuQ2R9IDYyTQAQVzUinneBCSSo6Hbxqva8zMwK8UCBSO14jqammiqMeSNkqSY13AGU4php9xn0guZUWCR6w93wxkOxMyWt2qlbPficXVX12PLwj1TTXix4REbcIhP-dt3Srsqa8MkR-yhdfmgEGJyJnY6-9RTE_wMweUJO3OY6hpC4ziOnvF5tirVKFgPSZA5CfTN-f3ZIc_4LsvjxlG66TvUeJdzeiZfUvEkOKhhaMkNjo0iPoMUkHzuorz6cthWwW6vzDCPyljjZNLPp3LIOJY3Pgv5ma3XjC3tsNVJXUe4FjG_I0/file?dl=1
Reusing existing connection to uc152a49a47dcfa5d06a5c3c8cb7.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 678640589 (647M) [application/binary]
Saving to: ‘stocks.parquet’

stocks.parquet      100%[===================>] 647.20M  55.0MB/s    in 11s

2026-01-09 02:34:37 (56.7 MB/s) - ‘stocks.parquet’ saved [678640589/678640589]

In [4]:
!ls stocks.parquet -l #downloaded file

-rw-r--r-- 1 root root 678640589 Jan  9 02:34 stocks.parquet

In [ ]:
#Bonus question 1 - find on internet and write the command that will download the all data from the symbols list.

In [5]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.1)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.11.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [12]:
import yfinance as yf

small_list = list(symbols)[:100]
symbols_data = yf.download(list(small_list), period="1wk", interval="1d")

/tmp/ipython-input-2013339825.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  symbols_data = yf.download(list(small_list), period="1wk", interval="1d")
[*********************100%***********************]  100 of 100 completed
ERROR:yfinance:
7 Failed downloads:
ERROR:yfinance:['BAC-N', 'GUT-C', 'GRAF=', 'JENA^', 'EVAC=', 'PERF+', 'PMT-A']: YFPricesMissingError('possibly delisted; no price data found  (period=1wk) (Yahoo error = "No data found, symbol may be delisted")')

In [13]:
symbols_data.head(5)

Price      Adj Close                                          Close  \
Ticker         BAC-N EVAC= GRAF= GUT-C JENA^ PERF+ PMT-A       ACLO
Date
2026-01-02       NaN   NaN   NaN   NaN   NaN   NaN   NaN  50.325001
2026-01-05       NaN   NaN   NaN   NaN   NaN   NaN   NaN  50.330002
2026-01-06       NaN   NaN   NaN   NaN   NaN   NaN   NaN  50.369999
2026-01-07       NaN   NaN   NaN   NaN   NaN   NaN   NaN  50.334999
2026-01-08       NaN   NaN   NaN   NaN   NaN   NaN   NaN  50.360001

Price                             ... Volume                                  \
Ticker            ADM       AFGD  ...   VEXC     VMI      VNM   VSLU    VTEC
Date                              ...
2026-01-02  59.049999  20.951000  ...  23800  133400   936300  37200  270100
2026-01-05  59.580002  21.000000  ...  37600  153100   662800  33300  230200
2026-01-06  60.490002  20.940001  ...  48600  207100  1584000  64800  285000
2026-01-07  58.520000  20.959999  ...  23400  154000  1125400  31800  261400
2026-01-08  61.189999  20.950001  ...  32400  236600   455100  23200  221700

Price
Ticker          WD      XPO      YPF     YYY ZCBB
Date
2026-01-02  261100   676000   947400  258900  NaN
2026-01-05  247900  1377700  1508100  356400  NaN
2026-01-06  284300  1817900  1844400  262200  NaN
2026-01-07  246800  1133000  2969200  264000  0.0
2026-01-08  217800  1463200  1535000  857900  2.0

[5 rows x 507 columns]

In [14]:
data=pd.read_parquet('stocks.parquet')

In [15]:
data.head(1) # Below shows a sample of the data.
#date - describes the day of the price
#open - the price at which stock opened
#high - what was the intraday high
#low - what is the intraday low
#close - what was the closing price
#adj_close - the price calculated after adjusting for all future stock splits
#dividends - what are the dividends that were paid on the day.
#stock_splits - if the stock was split
#symbol the symbol of the stock

,date,open,high,low,close,adj_close,volume,dividends,stock_splits,symbol,day,year,month,dayofweek
0,1962-01-02,0.131273,0.131273,0.124177,0.124177,0.045278,2480333.0,0.0,0.0,HPQ,2,1962,1,Tuesday

In [16]:
data[250:255]

,date,open,high,low,close,adj_close,volume,dividends,stock_splits,symbol,day,year,month,dayofweek
250,1962-12-28,0.086037,0.086480,0.085593,0.085593,0.031209,338227.0,0.0,0.0,HPQ,28,1962,12,Friday
251,1962-12-31,0.085593,0.086037,0.085593,0.085593,0.031209,1127424.0,0.0,0.0,HPQ,31,1962,12,Monday
252,1963-01-02,0.085593,0.086037,0.083376,0.083376,0.030401,789197.0,0.0,0.0,HPQ,2,1963,1,Wednesday
253,1963-01-03,0.083376,0.085150,0.082932,0.085150,0.031048,732826.0,0.0,0.0,HPQ,3,1963,1,Thursday
254,1963-01-04,0.085150,0.086924,0.085150,0.086924,0.031695,507341.0,0.0,0.0,HPQ,4,1963,1,Friday

In [22]:
# Question 2 find top 20 best performer stocks - i.e. the stocks that provided the best return.
# if the stocks adj_close on the earliest date was X and the adj_close on the 2021-01-01 is y and the number of days elapsed between these dates is Z.
# Then return = Y/X/Z
# Sort the stocks by this return and find the top 20

In [21]:
# find top 20 using first and last date of adj_close
data['date'] = pd.to_datetime(data['date'])

def find_stock_performance(symbol_data):
  symbol_data = symbol_data.sort_values('date')
  X = symbol_data['adj_close'].iloc[0]
  Y = symbol_data['adj_close'].iloc[-1]

  start_date = symbol_data['date'].iloc[0]
  end_date = symbol_data['date'].iloc[-1]
  Z = (end_date - start_date).days
  if Z <= 0 or X <= 0:
    return 0

  return Y/X/Z

results = data.groupby('symbol').apply(find_stock_performance, include_groups=False)
top_20 = results.sort_values(ascending=False).head(20)
print(top_20)

symbol
NVO      3.302876e+06
NKE      2.959418e+03
DCI      3.869564e+02
TJX      2.063167e+02
WTRG     7.221605e+00
TTC      6.224708e+00
USB      4.078555e+00
MCD      3.374097e+00
PII      2.554223e+00
HD       1.506773e+00
IQMD     1.001014e+00
AOGOU    9.990020e-01
PCCT     9.959839e-01
ETN      9.076372e-01
FRLAW    8.888889e-01
HAS      7.035260e-01
KO       6.680578e-01
MO       6.485381e-01
KOL      5.786728e-01
HRL      5.406652e-01
dtype: float64

In [24]:
# find top 20 using first date and 2021-1-1 of adj_close
data['date'] = pd.to_datetime(data['date'])
target = pd.Timestamp('2021-01-01')

def find_stock_performance(symbol_data):
    symbol_data = symbol_data.sort_values('date')
    X = symbol_data['adj_close'].iloc[0]

    # restrict to target time for Y
    upto = symbol_data[symbol_data['date'] <= target]
    if upto.empty:
        return pd.NA
    Y = upto['adj_close'].iloc[-1]

    start_date = symbol_data['date'].iloc[0]
    end_date = upto['date'].iloc[-1]
    Z = (end_date - start_date).days
    if Z <= 0 or X <= 0:
        return pd.NA

    return Y/X/Z

results = data.groupby('symbol').apply(find_stock_performance, include_groups=False).dropna()
top_20 = results.sort_values(ascending=False).head(20)
print(top_20)

symbol
NVO     2078044.428985
NKE        2540.825231
DCI          376.88598
TJX         192.384422
WTRG          6.511958
TTC           5.989074
USB           3.342177
MCD           2.686572
PII           2.294361
SPRE          1.007353
AVDR          1.005687
AVDG          1.003997
PSFF          1.003692
DUDE               1.0
KNGS           0.99543
HD            0.994592
CBTG          0.991758
HAS           0.664501
ETN           0.639233
KO            0.615714
dtype: object

In [ ]:
#Question 3: Create a copy of this notebook called assignment-aws and follow the instructions in readme to run the notebook on AWS compute instance.
# Compare performance of running natively on colab and colab+AWS